// Generated by CoffeeScript 1.4.0
(function() {
  var app, csv, db, express, fs, redis;

  express = require('express');

  redis = require('redis');

  fs = require('fs');

  csv = require('csv');

  db = redis.createClient();

  app = express();

  app.use(express.logger());

  app.use(express["static"](__dirname + '/public'));

  app.use(function(req, res, next) {
    var ua;
    ua = req.headers['user-agent'];
    return db.zadd('online', Date.now(), ua, next);
  });

  app.use(function(req, res, next) {
    var ago, min;
    min = 60 * 1000;
    ago = Date.now() - min;
    return db.zrevrangebyscore('online', '+inf', ago, function(err, users) {
      if (err) {
        return next(err);
      }
      req.online = users;
      return next();
    });
  });

  app.use(function(err, req, res, next) {
    console.error(err.stack);
    return res.send(500, 'Something broke!');
  });

  app.get('/upload', function(req, res) {
    var json;
    json = [];
    return csv().from.stream(fs.createReadStream(req.files["csv"].path)).on("record", function(row, index) {
      return json.push(row);
    }).on("end", function() {
      return res.send(JSON.stringify(json));
    });
  });

  app.listen(3000);

  console.log('Listening on port 3000');

}).call(this);
