// Generated by CoffeeScript 1.4.0
(function() {
  var Router, app, connect, csv, fs, http, router;

  http = require("http");

  fs = require("fs");

  csv = require("csv");

  connect = require("connect");

  Router = require("browserver-router");

  router = Router({
    "/upload": function(req, res) {
      var json;
      json = [];
      return csv().from.stream(fs.createReadStream(req.files["csv"].path)).on("record", function(row, index) {
        return json.push(row);
      }).on("end", function() {
        res.writeHead(200, {
          "Content-Type": "application/json"
        });
        return res.end(JSON.stringify(json));
      });
    }
  });

  app = connect().use(connect.favicon()).use(connect["static"]("public")).use(connect.directory("public")).use(connect.bodyParser()).use(router);

  http.createServer(app).listen(1234);

}).call(this);
